# Generated by Django 3.1 on 2020-11-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201114_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='desc',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1', to='network.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2', to='network.profile'),
        ),
    ]
