# Generated by Django 3.1 on 2020-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_present_like',
            field=models.BooleanField(default=False),
        ),
    ]
