# Generated by Django 3.1 on 2020-11-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_user_present_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_present_like',
        ),
    ]
