# Generated by Django 3.1 on 2020-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_user_present_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
